# Goal
float32 turn_angle       # angle to turn to in degrees
float32 angular_velocity # turn speed in degrees / sec
---
# Result
float32 last_angle    # current_angle + turn_angle if successful
float32 elapsed_time  # in seconds
bool success          # true if robot turned, false if not
string message        # error or status message
